bios_header:
    mov {CONFIG_TTY_STDOUT}, #'V'
    mov {CONFIG_TTY_STDOUT}, #'i'
    mov {CONFIG_TTY_STDOUT}, #'x'
    mov {CONFIG_TTY_STDOUT}, #'e'
    mov {CONFIG_TTY_STDOUT}, #'n'
    mov {CONFIG_TTY_STDOUT}, #' '
    mov {CONFIG_TTY_STDOUT}, #'K'
    mov {CONFIG_TTY_STDOUT}, #'i'
    mov {CONFIG_TTY_STDOUT}, #'c'
    mov {CONFIG_TTY_STDOUT}, #'k'
    mov {CONFIG_TTY_STDOUT}, #'s'
    mov {CONFIG_TTY_STDOUT}, #'t'
    mov {CONFIG_TTY_STDOUT}, #'a'
    mov {CONFIG_TTY_STDOUT}, #'r'
    mov {CONFIG_TTY_STDOUT}, #'t'
    mov {CONFIG_TTY_STDOUT}, #' '
    mov {CONFIG_TTY_STDOUT}, #'['
    mov {CONFIG_TTY_STDOUT}, #'R'
    mov {CONFIG_TTY_STDOUT}, #'e'
    mov {CONFIG_TTY_STDOUT}, #'v'
    mov {CONFIG_TTY_STDOUT}, #'i'
    mov {CONFIG_TTY_STDOUT}, #'s'
    mov {CONFIG_TTY_STDOUT}, #'i'
    mov {CONFIG_TTY_STDOUT}, #'o'
    mov {CONFIG_TTY_STDOUT}, #'n'
    mov {CONFIG_TTY_STDOUT}, #' '
    mov {CONFIG_TTY_STDOUT}, #'1'
    mov {CONFIG_TTY_STDOUT}, #']'
    mov {CONFIG_TTY_STDOUT}, #$d
    mov {CONFIG_TTY_STDOUT}, #$a
    ret
